language: node_js
node_js:
  - "10"

services:
  - docker

before_install:
- sudo service mysql stop
- docker-compose -f ./test/docker-compose.yml up -d
# Wait for database being ready
- while ! echo exit | nc localhost 3306; do sleep 10; done
- npm install


script:
- npm run test-dev

deploy:
  provider: script
  skip_cleanup: true
  script: './publish.sh'
  on:
    tags: true
    branch: master